### ISSUE TITLE
Unable to open connection to bench target <target-name>

### ISSUE THREAD

**Issue by seatonullberg** [bheisler/criterion.rs#466]
I have a benchmark test that previously worked with criterion:

```rust
pub fn velocity_verlet_benchmark(c: &mut Criterion) {
    let file = File::open(test_utils::test_resources_path("argon.poscar")).unwrap();
    let reader = BufReader::new(file);
    let mut system = load_poscar(reader);

    let target = 100 as f32;
    let boltz = Boltzmann::new(target);
    boltz.apply(&mut system);

    let potentials = test_utils::get_argon_potentials(&system);

    let mut vv = VelocityVerlet::new(1.0);
    vv.setup(&system, &potentials);

    c.bench_function("velocity_verlet", |b| {
        b.iter(|| vv.integrate(&mut system, &potentials))
    });
}

criterion_group!(integrators, velocity_verlet_benchmark);
criterion_main!(integrators);
```

When I run `cargo criterion` in my crate's root I generate the following backtrace:

```
Error: Unable to open connection to bench target integrator-benchmarks

Caused by:
    Resource temporarily unavailable (os error 35)
Gnuplot not found, using plotters backend                                                            
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: IoError(Os { code: 32, kind: BrokenPipe, message: "Broken pipe" })', /Users/seaton/.cargo/registry/src/github.com-1ecc6299db9ec823/criterion-0.3.4/src/lib.rs:1105:18
stack backtrace:
   0:        0x10b506034 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::ha0848bb2602b5d05
   1:        0x10b5297c0 - core::fmt::write::h9f3ccac2ef682b93
   2:        0x10b500a66 - std::io::Write::write_fmt::h0a47673aab280496
   3:        0x10b507e19 - std::panicking::default_hook::{{closure}}::h850c6aaf5e80c2f5
   4:        0x10b507add - std::panicking::default_hook::h037801299da6e1c6
   5:        0x10b50849b - std::panicking::rust_panic_with_hook::h76436d4cf7a368ac
   6:        0x10b507fc5 - std::panicking::begin_panic_handler::{{closure}}::h516c76d70abf04f6
   7:        0x10b5064a8 - std::sys_common::backtrace::__rust_end_short_backtrace::h653290b4f930faed
   8:        0x10b507f2a - _rust_begin_unwind
   9:        0x10b5465af - core::panicking::panic_fmt::hde9134dd19c9a74f
  10:        0x10b5464b5 - core::result::unwrap_failed::hcef4aa8b48b8f381
  11:        0x10b21911f - criterion::Criterion<M>::bench_function::ha97393c876f4a9c2
  12:        0x10b20fe7e - integrator_benchmarks::main::hc4380f5db0e61bf1
  13:        0x10b20dc3a - std::sys_common::backtrace::__rust_begin_short_backtrace::h900a22971ad5dd20
  14:        0x10b231d9c - std::rt::lang_start::{{closure}}::hb8e376b3f2b1b1ce
  15:        0x10b5088f4 - std::rt::lang_start_internal::h36ccce6e8a047133
  16:        0x10b210079 - _main
```

I have been able to run the same benchmark with no problems using `cargo bench`:

```
velocity_verlet         time:   [144.16 us 144.62 us 145.39 us]                            
                        change: [-0.8380% +0.3702% +2.0284%] (p = 0.62 > 0.05)
                        No change in performance detected.
Found 8 outliers among 100 measurements (8.00%)
  1 (1.00%) low mild
  2 (2.00%) high mild
  5 (5.00%) high severe
```

**Comment by bheisler** [comment]
Hey, thanks for the bug report, and thanks for trying cargo-criterion. Unfortunately, I'm afraid I don't have enough information yet to diagnose this problem. Could you try running the benchmarks with `cargo criterion --debug`? That way at least they're built with all of the debug information and I can get a complete backtrace, at least.

**Comment by seatonullberg** [comment]
Unfortunately, I've since made a lot of changes to my workstation and the code so I can no longer replicate the issue. Sorry I can't provide more info for others who may experience this.

**Comment by Shadow53** [comment]
I am getting this same issue, so I'd like to reopen the issue with my information. I have just started writing the benchmarks, so I do not have a previously working version. This is using `cargo criterion`.

I have the following code (constants and helper functions elided):

```rust
fn criterion_benchmark(c: &mut Criterion) {
    let mut group = c.benchmark_group("Databases");
    let data = get_data();
    let tokio_executor = tokio::runtime::Runtime::new()
        .expect("failed to initialize tokio runtime");

    let json_pool = tokio_executor.block_on(get_pg_json_pool());

    tokio_executor.block_on(with_json::init(&json_pool)).expect("failed to initialization postgres database (JSON)");

    for (i, datum) in data.into_iter().enumerate() {
        group.bench_with_input(BenchmarkId::new("Postgres (JSON)", i), &datum, |b, datum| {
            b.to_async(&tokio_executor).iter(|| with_json::upsert(&json_pool, datum))
        });
    }
}

criterion_group!(benches, criterion_benchmark);
criterion_main!(benches);
```

And the error with full stack trace (I use a Makefile to set up docker databases before running benchmarks):

```
Error: Unable to open connection to bench target databases

Caused by:
    Resource temporarily unavailable (os error 35)
make: *** [criterion] Error 1
Gnuplot not found, using plotters backend
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: IoError(Os { code: 32, kind: BrokenPipe, message: "Broken pipe" })', /Users/mbryant/.cargo/registry/src/github.com-1ecc6299db9ec823/criterion-0.3.4/src/lib.rs:1105:18
stack backtrace:
   0:        0x10c48d274 - std::backtrace_rs::backtrace::libunwind::trace::h2973c0f115cf39cb
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/../../backtrace/src/backtrace/libunwind.rs:100:5
   1:        0x10c48d274 - std::backtrace_rs::backtrace::trace_unsynchronized::h1a2874ce966099c0
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:        0x10c48d274 - std::sys_common::backtrace::_print_fmt::h3b860fb438483fb1
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/sys_common/backtrace.rs:67:5
   3:        0x10c48d274 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::ha0848bb2602b5d05
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/sys_common/backtrace.rs:46:22
   4:        0x10c4b10a0 - core::fmt::write::h9f3ccac2ef682b93
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/core/src/fmt/mod.rs:1078:17
   5:        0x10c487166 - std::io::Write::write_fmt::h0a47673aab280496
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/io/mod.rs:1518:15
   6:        0x10c48f079 - std::sys_common::backtrace::_print::h9c13ab471b84d474
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/sys_common/backtrace.rs:49:5
   7:        0x10c48f079 - std::sys_common::backtrace::print::h075217710b715efc
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/sys_common/backtrace.rs:36:9
   8:        0x10c48f079 - std::panicking::default_hook::{{closure}}::h850c6aaf5e80c2f5
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panicking.rs:208:50
   9:        0x10c48ed3d - std::panicking::default_hook::h037801299da6e1c6
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panicking.rs:227:9
  10:        0x10c48f6fb - std::panicking::rust_panic_with_hook::h76436d4cf7a368ac
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panicking.rs:593:17
  11:        0x10c48f225 - std::panicking::begin_panic_handler::{{closure}}::h516c76d70abf04f6
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panicking.rs:499:13
  12:        0x10c48d6e8 - std::sys_common::backtrace::__rust_end_short_backtrace::h653290b4f930faed
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/sys_common/backtrace.rs:141:18
  13:        0x10c48f18a - rust_begin_unwind
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panicking.rs:495:5
  14:        0x10c4c61ef - core::panicking::panic_fmt::hde9134dd19c9a74f
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/core/src/panicking.rs:92:14
  15:        0x10c4c60f5 - core::option::expect_none_failed::h686aad664d56bca5
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/core/src/option.rs:1268:5
  16:        0x10b911b47 - core::result::Result<T,E>::unwrap::h7dd44e9b7377718c
                               at /Users/mbryant/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/result.rs:973:23
  17:        0x10b91a559 - criterion::Criterion<M>::benchmark_group::hf7a0536fc9f2face
                               at /Users/mbryant/.cargo/registry/src/github.com-1ecc6299db9ec823/criterion-0.3.4/src/lib.rs:1104:13
  18:        0x10b8e9693 - databases::criterion_benchmark::hd5ce7b92deb0cdd0
                               at /Users/mbryant/Development/database-benchmark/benches/databases.rs:28:21
  19:        0x10b8e9ae6 - databases::benches::hcc289c4797fadf8e
                               at /Users/mbryant/.cargo/registry/src/github.com-1ecc6299db9ec823/criterion-0.3.4/src/macros.rs:71:17
  20:        0x10b8e9b3a - databases::main::h1b8210a153ce36cc
                               at /Users/mbryant/.cargo/registry/src/github.com-1ecc6299db9ec823/criterion-0.3.4/src/macros.rs:127:17
  21:        0x10b913b6e - core::ops::function::FnOnce::call_once::h1d3011c1f7f8f843
                               at /Users/mbryant/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/ops/function.rs:227:5
  22:        0x10b8d9911 - std::sys_common::backtrace::__rust_begin_short_backtrace::h0f988bd6fdec4b82
                               at /Users/mbryant/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/std/src/sys_common/backtrace.rs:125:18
  23:        0x10b8f0c54 - std::rt::lang_start::{{closure}}::h1aa99daa498ec43d
                               at /Users/mbryant/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/std/src/rt.rs:66:18
  24:        0x10c48fb54 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h81f763a559f81b5c
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/core/src/ops/function.rs:259:13
  25:        0x10c48fb54 - std::panicking::try::do_call::h8f7e7501b4b6c841
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panicking.rs:381:40
  26:        0x10c48fb54 - std::panicking::try::h5def58989e0f2c84
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panicking.rs:345:19
  27:        0x10c48fb54 - std::panic::catch_unwind::h8210e1d7d92e8f91
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panic.rs:396:14
  28:        0x10c48fb54 - std::rt::lang_start_internal::h36ccce6e8a047133
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/rt.rs:51:25
  29:        0x10b8f0c31 - std::rt::lang_start::heda51adf0ea8bc88
                               at /Users/mbryant/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/std/src/rt.rs:65:5
  30:        0x10b8e9bc2 - _main
```

**Comment by jecolasurdo** [comment]
Hi there, I am also experiencing a similar (if not the same) error when running `cargo criterion`.

I don't intend to pig-pile on an issue that has already been documented, but am hoping that this example might help provide some additional data points since it doesn't involve docker or an async framework. As I type this, I wonder if the similar thread between my experience and that of @Shadow53 is that both of our benchmarks require access to an external resource _(mine requiring filesystem access, and theirs requiring access to a datastore within docker)_. Just a theory.

The project I'm using this within is open-source, so you can pull the code and try to replicate locally if you need. https://github.com/jecolasurdo/tbtlarchivist/blob/criterion/rust/analyzer/benches/benchmark.rs

Benchmark code:
```rust
use analyzer::engines::cosine_similarity::{self, Settings};
use analyzer::engines::Analyzer;
use criterion::{black_box, criterion_group, criterion_main, Criterion};
use std::fs::File;
use std::io::Read;

fn criterion_benchmark(c: &mut Criterion) {
    let sample_path = String::from(
        "/Users/Joe/Documents/code/tbtlarchivist/rust/analyzer/benches/drop_5000_samples.mp3",
    );
    let mut file = File::open(sample_path).unwrap();
    let mut data = Vec::new();
    file.read_to_end(&mut data).unwrap();

    // values in engine_settings don't matter for this benchmark.
    let engine_settings = Settings {
        pass_one_sample_density: 1,
        pass_one_sample_size: 9,
        pass_one_threshold: 0.991,
        pass_two_sample_size: 50,
        pass_two_threshold: 0.99,
    };

    let engine = cosine_similarity::new(engine_settings);
    c.bench_function("mp3_to_raw", |b| {
        b.iter(|| engine.mp3_to_raw(black_box(&data)))
    });
}

criterion_group!(benches, criterion_benchmark);
criterion_main!(benches);
```

Output:
```bash
☸ k3d-west in tbtlarchivist/rust on  criterion
02:00:22 AM ❯ export RUST_BACKTRACE=1 && cargo criterion --debug
   Compiling analyzer v0.1.0 (/Users/Joe/Documents/code/tbtlarchivist/rust/analyzer)
    Finished test [unoptimized + debuginfo] target(s) in 5.31s

running 1 test
test engines::cosine_similarity::tests::cosine_sim_happy_path ... ignored

test result: ok. 0 passed; 0 failed; 1 ignored; 0 measured; 0 filtered out; finished in 0.00s

Error: Unable to open connection to bench target benchmark

Caused by:
    Resource temporarily unavailable (os error 35)
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: IoError(Os { code: 32, kind: BrokenPipe, message: "Broken pipe" })', /Users/Joe/.cargo/registry/src/github.com-1ecc6299db9ec823/criterion-0.3.4/src/lib.rs:1105:18
stack backtrace:
☸ k3d-west in tbtlarchivist/rust on  criterion took 6s
02:00:46 AM ❯    0: rust_begin_unwind
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/panicking.rs:92:14
   2: core::option::expect_none_failed
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/option.rs:1268:5
   3: core::result::Result<T,E>::unwrap
             at /Users/Joe/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/result.rs:973:23
   4: criterion::Criterion<M>::benchmark_group
             at /Users/Joe/.cargo/registry/src/github.com-1ecc6299db9ec823/criterion-0.3.4/src/lib.rs:1104:13
   5: criterion::Criterion<M>::bench_function
             at /Users/Joe/.cargo/registry/src/github.com-1ecc6299db9ec823/criterion-0.3.4/src/lib.rs:1140:9
   6: benchmark::criterion_benchmark
             at ./analyzer/benches/benchmark.rs:22:5
   7: benchmark::benches
             at /Users/Joe/.cargo/registry/src/github.com-1ecc6299db9ec823/criterion-0.3.4/src/macros.rs:71:17
   8: benchmark::main
             at /Users/Joe/.cargo/registry/src/github.com-1ecc6299db9ec823/criterion-0.3.4/src/macros.rs:127:17
   9: core::ops::function::FnOnce::call_once
             at /Users/Joe/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by Mazwak** [comment]
I have the same error on Windows.

With "os error 10035" : https://docs.microsoft.com/en-us/windows/win32/winsock/windows-sockets-error-codes-2

**Comment by bheisler** [comment]
For what it's worth - I too have run into this issue. It seems to disappear on its own for mysterious reasons though, so I've never been able to figure it out. I'll keep my eye on it.

**Comment by lemmih** [comment]
I believe this is related to https://github.com/bheisler/cargo-criterion/issues/12

Will test whether https://github.com/bheisler/cargo-criterion/pull/34 fixes it.

**Comment by lemmih** [comment]
I can't reproduce this. I'm fairly sure this was fixed by https://github.com/bheisler/cargo-criterion/pull/34 but I'm not 100% certain.

I will leave this issue open for another month and close it at the end of August if no one complains. Of course, if anyone encounters this after August, feel free to re-open.

**Comment by lemmih** [comment]
No further reports of failures. Closing issue.

**Comment by Kixiron** [comment]
I'm still encountering this error with v1.1.0 over [this repo](https://github.com/Kixiron/database-stream-processor/tree/cf38cee060f3d8174b2cb4685cd2404b41ac8dd7) in PowerShell v7.2.6
```
 λ  cargo criterion --version
cargo-criterion 1.1.0

 λ  $env:RUST_BACKTRACE = "full"
 
 λ  cargo criterion consolidation
    Finished bench [optimized + debuginfo] target(s) in 0.64s
Gnuplot not found, using plotters backend
Error: Failed to receive message from Criterion.rs benchmark target column_leaf

Caused by:
    An existing connection was forcibly closed by the remote host. (os error 10054)

Stack backtrace:
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: BaseThreadInitThunk
  13: RtlUserThreadStart
  ```
Other relevant versions:
  ```
   λ  rustc -Vv
rustc 1.65.0-nightly (17cbdfd07 2022-09-13)
binary: rustc
commit-hash: 17cbdfd07178349d0a3cecb8e7dde8f915666ced
commit-date: 2022-09-13
host: x86_64-pc-windows-msvc
release: 1.65.0-nightly
LLVM version: 15.0.0

 λ  cargo -Vv
cargo 1.65.0-nightly (646e9a0b9 2022-09-02)
release: 1.65.0-nightly
commit-hash: 646e9a0b9ea8354cc409d05f10e8dc752c5de78e
commit-date: 2022-09-02
host: x86_64-pc-windows-msvc
libgit2: 1.5.0 (sys:0.15.0 vendored)
libcurl: 7.83.1-DEV (sys:0.4.55+curl-7.83.1 vendored ssl:Schannel)
os: Windows 10.0.19044 (Windows 10 Home) [64-bit]
```

**Comment by caass** [comment]
Necroposting to report I'm experiencing it [here](https://github.com/caass/advent-of-code/actions/runs/12230092041/job/34111006539#step:8:117), but only on windows.
