### ISSUE TITLE
Won't Compile 1.52.0-nightly (35dbef235 2021-03-02)

### ISSUE THREAD

**Issue by zeroflaw** [bheisler/criterion.rs#468]
```
error: unknown "doc" attribute "Hidden"
  --> /Users/xxx/.cargo/registry/src/github.com-1ecc6299db9ec823/tinytemplate-1.1.0/src/error.rs:44:11
   |
44 |     #[doc(Hidden)]
   |           ^^^^^^

error: aborting due to previous error

error: could not compile "tinytemplate"
```

Might need to bump dependency see, https://github.com/bheisler/TinyTemplate/pull/17

**Comment by bheisler** [comment]
Hey, thanks for the report. It should be fixed now.

For future reference, there was a regression in nightly builds of the compiler which TinyTemplate happened to trip over: https://github.com/bheisler/TinyTemplate/pull/17

I've published a new version of TinyTemplate which should fix this. You may need to use `cargo update` or similar to update your lockfile to TinyTemplate 1.2.1.

**Comment by danielhstahl** [comment]
This still doesn't work for me.  See https://github.com/realoptions/option_price_faas/runs/2030977950?check_suite_focus=true

Even though my lock has 1.2.1 it still downloads 1.1.0.

**Comment by zeroflaw** [comment]
Yeah this needs bumping

https://github.com/bheisler/criterion.rs/blob/cee63459dc58f86a9c319bd4fa7e762f7c333bf6/Cargo.toml#L28

**Comment by danielhstahl** [comment]
Ah, it didn't work because it was comparing my master branch which had the old 1.1.1 rather than 1.2.1.
